config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'
  resources :articles 
  resources :actions
  resources :category
  resources :benefit
  resources :defect
  resources :symptom
  resources :problem
  resources :effect
  resources :interface

end

app/models/action.rb
class Action < ActiveRecord::Base
	has_many :actions_symptoms
	has_many :symptoms, through: :actions_symptoms 
	
	has_many :actions_defects
	has_many :defects, through: :actions_defects
	
	has_many :actions_benefits
	has_many :benefits, through: :actions_benefits 
	
	belongs_to :category
	
	accepts_nested_attributes_for :benefits
	accepts_nested_attributes_for :defects
	
	def to_s
		name
	end
end

app/models/actions_benefit.rb
class ActionsBenefit < ActiveRecord::Base
	belongs_to :action
	belongs_to :benefit
end

app/models/actions_defect.rb
class ActionsDefect < ActiveRecord::Base
	belongs_to :action
	belongs_to :defect
end

app/models/actions_symptom.rb
class ActionsSymptom < ActiveRecord::Base
	belongs_to :action
	belongs_to :symptom
end

app/models/benefit.rb
class Benefit < ActiveRecord::Base
	has_many :actions_benefits
	has_many :actions, through: :actions_benefits
	
	
	def to_s
		content
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :actions

	
	def to_s
		name
	end
end

app/models/defect.rb
class Defect < ActiveRecord::Base
	has_many :actions_defects
	has_many :actions, through: :actions_defects
	
	def to_s
		content
	end
end

app/models/symptom.rb
class Symptom < ActiveRecord::Base
	has_many :actions_symptoms
	has_many :actions, through: :actions_symptoms
	
	accepts_nested_attributes_for :actions
		
	def to_s
		name
	end
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "76x76#>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :avatar, attachment_presence: true
  validates :name, presence: true
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
	
	def index
    @actions = Action.all
  end

	def show
    		@action = Action.find(params[:id])
  end
  
	def update
  @action = Action.find(params[:id])
 
	  if @action.update(action_params)
	    redirect_to @action
	  else
	    render 'edit'
	  end
	end

	def edit
	  @action = Action.find(params[:id])
	end

	def new
  	@action = Action.new
	end
  
  def create
  @action = Action.new(action_params)
 	
 
  if @action.save
    redirect_to interface_index_path
  else
    render 'new'
  end
end

def destroy
	  @action = Action.find(params[:id]) 
	  @action.destroy
	 
	  redirect_to actions_path 
	end
  	
 
private
  	def action_params
    		params.require(:action_object).permit(:name, :category_id, :benefit_ids=> [],
    		:defect_ids => [])
  		
  	end
end

app/controllers/benefit_controller.rb
class BenefitController < ApplicationController
	def index
    @benefits = Benefit.all
  end

	def show
    @benefit = Benefit.find(params[:id])
  end

	def update
  @benefit = Benefit.find(params[:id])
 
  if @benefit.update(benefit_params)
    redirect_to @benefit
  else
    render 'edit'
  end
end

	def edit
	  @benefit = Benefit.find(params[:id])
	end

	def new
  	@benefit = Benefit.new
	end
  
  def create
  @benefit = Benefit.new(benefit_params)
 	
   if @benefit.save
   redirect_to interface_index_path
  else
   render 'new'
	end
end

def destroy
	  @benefit = Benefit.find(params[:id]) 
	  @benefit.destroy
	 
	  redirect_to benefit_index_path 
	end
  	
 
private
  	def benefit_params
    		params.require(:benefit).permit(:content)
  	end
end

app/controllers/defect_controller.rb
class DefectController < ApplicationController
	def index
    @defects = Defect.all
  end

	def show
    		@defect = Defect.find(params[:id])
  end

	def update
	  @defect = Defect.find(params[:id])
	 
	  if @defect.update(defect_params)
	    redirect_to @defect
	  else
	    render 'edit'
	  end
	end

	def edit
	  @defect = Defect.find(params[:id])
	end

	def new
  	@defect = Defect.new
	end
  
  def create
	  @defect = Defect.new(defect_params)
	 	
	 
	  if @defect.save
	    redirect_to interface_index_path
	  else
	    render 'new'
	  end
	end
  
  def destroy
	  @defect = Defect.find(params[:id]) 
	  @defect.destroy
	 
	  redirect_to defect_index_path 
	end
	

  	
 
private
  	def defect_params
    		params.require(:defect).permit(:content)
  	end
end

app/controllers/effect_controller.rb
class EffectController < ApplicationController
  def index
  	@actions = Action.all
  	@category = Category.all
  	@benefit = Benefit.all
  	
  end
  
  def show
		#@category = Category.find(params[:id])
		@actions = Action.find(params[:data_name])
		@category = Category.find(params[:data_name])
	end
	
	def show_benefit(param)
		@actions = Action.find_by name: param
	end
	
	#def
	#	@
	#end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/benefit_helper.rb
module BenefitHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/defect_helper.rb
module DefectHelper
end

app/helpers/effect_helper.rb
module EffectHelper
end

app/helpers/interface_helper.rb
module InterfaceHelper
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/helpers/symptom_helper.rb
module SymptomHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/benefit/edit.html.erb
<h1>Editing benefit</h1>
 
<%= form_for :benefit, url: benefit_path(@benefit), method: :patch do |f| %>
 

 
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>
 

 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', benefits_path %>

app/views/benefit/index.html.erb

<h1> It works</h1>
<table>
	<p>
		<h2>Name</h2>
	<p>
	  <% @benefits.each do |benefit| %>
	    <tr>
	      <td><%= benefit.content %></li> 
	      <td><%= link_to 'Show', benefit_path(benefit) %></td>
     		<td><%= link_to 'Edit', edit_benefit_path(benefit) %></td> 
     		     		<td><%= link_to 'Destroy', benefit_path(benefit),
              method: :delete %>
        </td> 
	    </tr>
	  <% end %>
	</p>
</table>

app/views/benefit/new.html.erb
<h1> New benefit </h1>
<%= form_for :benefit, url: benefit_index_path do |f| %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', benefit_index_path %>

app/views/benefit/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @benefit.content %>
</p>

<%= link_to 'Edit', edit_benefit_path(@benefit) %>
 

app/views/defect/edit.html.erb
<h1>Editing defect</h1>
 
<%= form_for :defect, url: defect_path(@defect), method: :patch do |f| %>
 

 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 

 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', defects_path %>

app/views/defect/index.html.erb
<table>
	  <% @defects.each do |defect| %>
	    <tr>
	      <td><%= defect.content %></li> 
	      <td><%= link_to 'Show', defect_path(defect) %></td>
     		<td><%= link_to 'Edit', edit_defect_path(defect) %></td>
     		<td><%= link_to 'Destroy', defect_path(defect),
              method: :delete %>
        </td> 
	    </tr>
	  <% end %>

</table>

app/views/defect/new.html.erb
<h1> New defect </h1>
<%= form_for :defect, url: defect_index_path do |f| %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', defect_index_path %>

app/views/defect/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @defect.content %>
</p>

<%= link_to 'Edit', edit_defect_path(@defect) %>
<%= link_to 'Back', defect_path %>
 