config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'
  resources :articles 
  resources :actions
  resources :category
  resources :benefit
  resources :defect
  resources :symptom
  resources :problem
  resources :effect
  resources :interface

end

app/models/action.rb
class Action < ActiveRecord::Base
	has_many :actions_symptoms
	has_many :symptoms, through: :actions_symptoms 
	
	has_many :actions_defects
	has_many :defects, through: :actions_defects
	
	has_many :actions_benefits
	has_many :benefits, through: :actions_benefits 
	
	belongs_to :category
	
	accepts_nested_attributes_for :benefits
	accepts_nested_attributes_for :defects
	
	def to_s
		name
	end
end

app/models/actions_benefit.rb
class ActionsBenefit < ActiveRecord::Base
	belongs_to :action
	belongs_to :benefit
end

app/models/actions_defect.rb
class ActionsDefect < ActiveRecord::Base
	belongs_to :action
	belongs_to :defect
end

app/models/actions_symptom.rb
class ActionsSymptom < ActiveRecord::Base
	belongs_to :action
	belongs_to :symptom
end

app/models/benefit.rb
class Benefit < ActiveRecord::Base
	has_many :actions_benefits
	has_many :actions, through: :actions_benefits
	
	
	def to_s
		content
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :actions

	
	def to_s
		name
	end
end

app/models/defect.rb
class Defect < ActiveRecord::Base
	has_many :actions_defects
	has_many :actions, through: :actions_defects
	
	def to_s
		content
	end
end

app/models/symptom.rb
class Symptom < ActiveRecord::Base
	has_many :actions_symptoms
	has_many :actions, through: :actions_symptoms
	
	accepts_nested_attributes_for :actions
		
	def to_s
		name
	end
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "76x76#>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :avatar, attachment_presence: true
  validates :name, presence: true
end

app/controllers/defect_controller.rb
class DefectController < ApplicationController
	def index
    @defects = Defect.all
  end

	def show
    		@defect = Defect.find(params[:id])
  end

	def update
	  @defect = Defect.find(params[:id])
	 
	  if @defect.update(defect_params)
	    redirect_to @defect
	  else
	    render 'edit'
	  end
	end

	def edit
	  @defect = Defect.find(params[:id])
	end

	def new
  	@defect = Defect.new
	end
  
  def create
	  @defect = Defect.new(defect_params)
	 	
	 
	  if @defect.save
	    redirect_to interface_index_path
	  else
	    render 'new'
	  end
	end
  
  def destroy
	  @defect = Defect.find(params[:id]) 
	  @defect.destroy
	 
	  redirect_to defect_index_path 
	end
	

  	
 
private
  	def defect_params
    		params.require(:defect).permit(:content)
  	end
end

app/controllers/effect_controller.rb
class EffectController < ApplicationController
  def index
  	@actions = Action.all
  	@category = Category.all
  	@benefit = Benefit.all
  	
  end
  
  def show
		#@category = Category.find(params[:id])
		@actions = Action.find(params[:data_name])
		@category = Category.find(params[:data_name])
	end
	
	def show_benefit(param)
		@actions = Action.find_by name: param
	end
	
	#def
	#	@
	#end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@actions = Action.all
  	@category = Category.all
  	@benefit = Benefit.all
  	
  end
  
  def show
		#@category = Category.find(params[:id])
		@actions = Action.find(params[:data_name])
		@category = Category.find(params[:data_name])
	end
	
	def show_benefit(param)
		@actions = Action.find_by name: param
	end
	
	#def
	#	@
	#end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/benefit_helper.rb
module BenefitHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/defect_helper.rb
module DefectHelper
end

app/helpers/effect_helper.rb
module EffectHelper
end

app/helpers/interface_helper.rb
module InterfaceHelper
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/helpers/symptom_helper.rb
module SymptomHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <div class="col-md-12">
              <div class="section">
                <div class="container">
                  <div class="row">
                  	
                  	<div class="col-md-4">
                      <%= link_to image_tag("https://ununsplash.imgix.net/photo-1414637104192-f9ab9a0ee249?w=300&amp;q=50&amp;fm=jpg&amp;s=39603686d9062f5c4a5309a45e28264e", class: "center-block img-circle img-responsive"), problem_index_path, method: :get %>
                      <h2>Rozwiąż swoje dolegliwości</h2>
                      <p style="font-size:20px">Sprawdz co możesz zrobić z trapiącymi Cię problemami.</p>
                    </div>
                    <div class="col-md-4">
                    	<%= link_to image_tag("https://unsplash.imgix.net/photo-1421986527537-888d998adb74?w=300&amp;q=50&amp;fm=jpg&amp;s=e633562a1da53293c4dc391fd41ce41d", class: "center-block img-circle img-responsive"), effect_index_path, method: :get %>
                      <h2>Sprawdz efekty swoich działań</h2>
                      <p>Sprawdz jakie efekty niosą za sobą podjęte przez Ciebie akcje</p>
                    </div>
                    
                    <div class="col-md-4">
                    	<%= link_to image_tag("https://unsplash.imgix.net/photo-1423439793616-f2aa4356b37e?w=300&amp;q=50&amp;fm=jpg&amp;s=3b42f9c018b2712544debf4d6a4998ff", class: "center-block img-circle img-responsive"), interface_index_path, method: :get %>
                      <h2>Dodaj własne elementy</h2>
                      <p>Dodaj własne elementy i stwórz własną baze profilaktycznych wskazówek</p>
                    </div>
                    
                  </div>
                </div>
              </div>
              <br>
              <br>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/welcome/index2.html.erb
<!doctype html>
<html lang="en">
<head>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<style>   
	h1 { padding: .1em; margin: 0; }
  #products { float:left; width: 300px; margin-right: 2em;cursor:move; }
  #cover { } 
  
  .style_image {
  float: middle;
	}
  #cart { width: 300px; float: left; margin-top: 0; }
  /* style the list to maximize the droppable hitarea */
  #cart ol { margin: 0; padding: 1em 0 1em 3em;}
  #effect { float: left; width: 200px; margin-left: ; }
  </style>
	<script>
		
	$(function() {
    $( "#catalog" ).accordion();
    $( "#catalog div" ).draggable({
      appendTo: "body",
      helper: "clone",
     	cursor: "move" 
    });
    
    $( "#cart ol" ).droppable({
      activeClass: "ui-state-default",
      hoverClass: "ui-state-hover",
      accept: ":not(.ui-sortable-helper)",
      drop: function( event, ui ) {
        $( this ).find( ".placeholder" ).remove();
        $( "<li></li>" ).text( ui.draggable.text() ).appendTo( this );
        $("<li></li>").appendTo(("#effect ol")).text(ui.draggable.text());
        $("#effect ol").find( ".placeholder" ).remove();
        
        $.getJSON("actions/"+ui.draggable.attr('id') +".json", function(data) {
        	var items = [];
        	$.each( data.benefits, function( key, val ) {
			    	items.push( "<li>" + val.content + "</li>" );
			  	});
			  	$.each( data.defects, function( key, val ) {
			    	items.push( "<li>" + val.content + "</li>" );
			  	});
					$( "<ul/>", {
			    "class": "my-new-list",
			    html: items.join( "" )
			  }).appendTo( "#effect ol" );		
       	});   
      }
    }).sortable({
      items: "li:not(.placeholder)",
      sort: function() {
        // gets added unintentionally by droppable interacting with sortable
        // using connectWithSortable fixes this, but doesn't allow you to customize active/hoverClass options
        $( this ).removeClass( "ui-state-default" );
      }
    });
  });		
		
		
		
	</script>
</head>
<body data-spy="scroll">
    <div class="cover">
      <%= image_tag("high_tatras_min.jpg", :class => "style_image") %>
    </div>
    <div class="section section-success">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
          	
            <ul class="lead nav nav-justified nav-pills">
              <li class="active">
                <a>Efekty dzialan<i class="fa fa-star fa-fw"></i></a>
              </li>
              <li class="">
                <a href="/problem">Rozwiazanie problemow</a>
              </li>
              <li class="">
                <a href="#">Messages</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section">
              <div class="container">
                <div class="row">
                  <div class="col-md-4">
                  	<div id="products">
										  <h1 class="ui-widget-header">Actions</h1>
										  <div id="catalog" class: ui-widget-content ui-state-default>
										 			<%@category.each do |category| %>
														<h2><%= category.name %></h2>
														<div>
											 					<% category.actions.each do |action| %>
											 					<%= content_tag(:div, action.name , id: action.id) %>
												  	<% end %>
										 				</div>
										 			<% end %>
										 
										  </div>
										</div>
                  </div>	 
                  <div class="col-md-4">
                  	<div id="cart">
										  <h3 class="ui-widget-header">What you wanna check</h3>
										  <div class="ui-widget-content">
										    <ol>
										      <li class="placeholder">Add your items here</li>
										    </ol>
										  </div>
										</div>
                  	
                  </div>
                  <div class="col-md-4">
                  	
                  	<div id ="effect">
											<h3 class="ui-widget-header">Effects</h3>
												<div class="ui-widget-content">
												<ol>
													<li class="placeholder"> Your effect</li>
													</li>
												</ol>
											</div>
										</div>
                  	
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</body> 
</html> 