config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'
  resources :articles 
  resources :actions
  resources :category
  resources :benefit
  resources :defect
  resources :symptom
  resources :problem
  resources :effect
  resources :interface

end

app/models/action.rb
class Action < ActiveRecord::Base
	has_many :actions_symptoms
	has_many :symptoms, through: :actions_symptoms 
	
	has_many :actions_defects
	has_many :defects, through: :actions_defects
	
	has_many :actions_benefits
	has_many :benefits, through: :actions_benefits 
	
	belongs_to :category
	
	accepts_nested_attributes_for :benefits
	accepts_nested_attributes_for :defects
	
	def to_s
		name
	end
end

app/models/actions_benefit.rb
class ActionsBenefit < ActiveRecord::Base
	belongs_to :action
	belongs_to :benefit
end

app/models/actions_defect.rb
class ActionsDefect < ActiveRecord::Base
	belongs_to :action
	belongs_to :defect
end

app/models/actions_symptom.rb
class ActionsSymptom < ActiveRecord::Base
	belongs_to :action
	belongs_to :symptom
end

app/models/benefit.rb
class Benefit < ActiveRecord::Base
	has_many :actions_benefits
	has_many :actions, through: :actions_benefits
	
	
	def to_s
		content
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :actions

	
	def to_s
		name
	end
end

app/models/defect.rb
class Defect < ActiveRecord::Base
	has_many :actions_defects
	has_many :actions, through: :actions_defects
	
	def to_s
		content
	end
end

app/models/symptom.rb
class Symptom < ActiveRecord::Base
	has_many :actions_symptoms
	has_many :actions, through: :actions_symptoms
	
	accepts_nested_attributes_for :actions
		
	def to_s
		name
	end
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "76x76#>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :avatar, attachment_presence: true
  validates :name, presence: true
end

app/controllers/defect_controller.rb
class DefectController < ApplicationController
	def index
    @defects = Defect.all
  end

	def show
    		@defect = Defect.find(params[:id])
  end

	def update
	  @defect = Defect.find(params[:id])
	 
	  if @defect.update(defect_params)
	    redirect_to @defect
	  else
	    render 'edit'
	  end
	end

	def edit
	  @defect = Defect.find(params[:id])
	end

	def new
  	@defect = Defect.new
	end
  
  def create
	  @defect = Defect.new(defect_params)
	 	
	 
	  if @defect.save
	    redirect_to interface_index_path
	  else
	    render 'new'
	  end
	end
  
  def destroy
	  @defect = Defect.find(params[:id]) 
	  @defect.destroy
	 
	  redirect_to defect_index_path 
	end
	

  	
 
private
  	def defect_params
    		params.require(:defect).permit(:content)
  	end
end

app/controllers/effect_controller.rb
class EffectController < ApplicationController
  def index
  	@actions = Action.all
  	@category = Category.all
  	@benefit = Benefit.all
  	
  end
  
  def show
		#@category = Category.find(params[:id])
		@actions = Action.find(params[:data_name])
		@category = Category.find(params[:data_name])
	end
	
	def show_benefit(param)
		@actions = Action.find_by name: param
	end
	
	#def
	#	@
	#end
end

app/controllers/interface_controller.rb
class InterfaceController < ApplicationController

def index
    @actions = Action.all
    @categories = Category.all
    @benefits = Benefit.all
    @defects = Defect.all
    @symptoms = Symptom.all
end


def new
	@action = Action.new
	@category = Category.new
	@benefit = Benefit.new
	@defect = Defect.new
	@symptom = Symptom.new
end
  
def create
	  @action = Action.new(action_params)
	  @category = Category.new(category_params)
	  @benefit = Benefit.new(benefit_params)
	  @defect = Defect.new(defect_params)
	  @symptom = Symptom.new(symptom_params)
	
	  if @action.save
	    redirect_to @action
	  else
	    render 'new'
	  end
	  
	  if @category.save
	    redirect_to @category
	  else
	    render 'new'
	  end
	  
	  if @benefit.save
   redirect_to @benefit
  	else
   	render 'new'
		end
	  

    if @defect.save
    	
      render 'index'
    else
      render action: "new" 
    end
    
 	
		
	  if @symptom.save
    redirect_to @symptom
		else
    render 'new'
	end
  
end
	
private
	def action_params
		params.require(:action_object).permit(:name, :category_id, :benefit_ids=> [],
		:defect_ids => [])
	end
	
	def category_params
		params.require(:category).permit(:name)
	end
	
	def benefit_params
		params.require(:benefit).permit(:content)
	end
	
	def defect_params
		params.require(:defect).permit(:content)
	end
	
	def symptom_params
		params.require(:symptom).permit(:name, :action_ids => [])
	end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/benefit_helper.rb
module BenefitHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/defect_helper.rb
module DefectHelper
end

app/helpers/effect_helper.rb
module EffectHelper
end

app/helpers/interface_helper.rb
module InterfaceHelper
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/helpers/symptom_helper.rb
module SymptomHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/interface/index.html.erb
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <div class="col-md-12">
            <div class="section">
              <div class="container">
                <div class="row">
                  <div class="col-md-6">                    	
											<%= simple_form_for :action_object, url: actions_path do |f| %>
											  <p>
											    <%= f.input :name , label: 'Nowa akcja', placeholder: "Nazwa akcji", required: false %>
											  </p>
										  
											  <p>
											  	<%= f.label :Wybierz_zalety, hint: 'No special characters.' %>
													<%= f.collection_select(:benefit_ids, Benefit.all, :id, :content,
											                              {include_blank: false, :include_hidden => false},
											                              {:multiple => true}) %>
											  </p>
											  <p>
											    <%= f.label :Wybierz_wady %>                     
											  	<%= f.collection_select(:defect_ids, Defect.all, :id, :content,
											                              {include_blank: false, :include_hidden => false},
											                              {:multiple => true}) %>
											  </p>
											    <%= f.label :Wybierz_kategorie %>  
											    <%= f.collection_select(:category_id , Category.all, :id, :name) %>
											     

											    <%= f.button :submit, "Zapisz akcje" %>
											  </p>
											<% end %>
                  	
                  </div>
                  <div class="col-md-6">
											<p>
                  	<%= simple_form_for :symptom, url: symptom_index_path   do |f| %>
                  	<p>
										    <%= f.input :name, label: 'Nowy problem', placeholder: "Nazwa problemu", required: false %>			
													  	<%= f.collection_select(:action_ids, Action.all, :id, :name,
													                              {include_blank: false, :include_hidden => false},
													                              {:multiple => true}) %>
 															<div class = "form-group">
 															<%= f.input :avatar, as: :file %>
									
										  <%= f.button :submit, "Zapisz problem" %>
										  </div>
										  
										<% end %>
									</p>


										<%= simple_form_for :benefit, url: benefit_index_path, html: {class: "form-inline"}     do |f| %>
										  
										  	<div class = "form-group" >
										    <%= f.input :content , label: 'Nowa zaleta' , placeholder: "Treść zalety", required: false %> 
										    <%= f.button :submit , "Zapisz zalete"%>
										    </div>
										 
										<% end %>	
										

                  	<%= simple_form_for :defect, url: defect_index_path, html: {class: "form-inline"}  do |f| %>
										  <p>
										    <%= f.input :content ,label: 'Nowa wada', placeholder: "Treść wady", required: false %>
										    <%= f.button :submit , "Zapisz wade", data: { notice:'Your confirm message' } %>
										     
										  </p>
										<% end %>

                  </div>
                </div>
                
                  
                </div>
              </div>
            </div>
            <br>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>